version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - MasakiMisawa
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: micromatch
    versions:
    - 4.0.3
  - dependency-name: listr2
    versions:
    - 3.4.0
    - 3.4.2
    - 3.6.1
  - dependency-name: rxjs
    versions:
    - 6.6.4
  - dependency-name: husky
    versions:
    - 5.1.0
